version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: streaming_project_bd
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/streaming_project_bd?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      WAIT_FOR_DB: db:3306
    command: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "streaming-project.jar"]
